version: "3.7"

services:
  bot:
    image: iamkale/gdnbot2:2.1.5
    user: root
    environment:
      - DISCORD_BOT_TOKEN
      - GDN_API_TOKEN
      - PAPERTRAIL_HOST
      - PAPERTRAIL_PORT
      - SESSION_ID
      - SESSION_HASH
      - BBUSER_ID
      - BBPASSWORD
      - MIN_ACCOUNT_AGE_DAYS
    volumes:
      # Preserve the settings database on the host filesystem
      - ./settings.db:/usr/src/app/settings.db:rw
    networks:
      - gdn_network
    command: "npm run host"
    restart: unless-stopped:0

networks:
  # This allows GDNBot to communicate with the API server via Nginx.
  # see the backend's docker-compose.yml
  gdn_network:
    external: true
    name: backend-network
